apiVersion: v1
kind: Pod
metadata:
  labels:
    run: traffic
  name: traffic
  namespace: ecommerce
spec:
  containers:
  - env:
    - name: FRONTEND_HOST
      value: frontend
    - name: FRONTEND_PORT
      value: "8080"
    image: ddtraining/traffic-replay:latest
    name: traffic
  dnsPolicy: ClusterFirst
  restartPolicy: Always
