apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: trace-error-rate
  namespace: ecommerce
spec:
  args:
  - name: service-name
  - name: version
  metrics:
  - name: error-rate
    interval: 1m
    successCondition: default(result, 0) < 0.01
    failureLimit: 10
    provider:
      datadog:
        interval: 1m
        query: |
          sum:trace.flask.request.errors{env:prod,service:{{args.service-name}},version:{{args.version}}}.as_count() /
          sum:trace.flask.request.hits{env:prod,service:{{args.service-name}},version:{{args.version}}}.as_count()
