apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: trace-error-rate
  namespace: ecommerce
spec:
  args:
  - name: service-name
  metrics:
  - name: error-rate
    interval: 5m
    successCondition: result <= 0.01
    failureLimit: 3
    provider:
      datadog:
        interval: 5m
        query: |
          sum:trace.flask.request.errors{env:prod,service:{{args.service-name}},version:{{args.version}}}.as_rate() /
          sum:trace.flask.request.hits{env:prod,service:{{args.service-name}},version:{{args.version}}}.as_rate()
