apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-discounts
  namespace: argocd
spec:
  destination:
    namespace: ecommerce
    server: https://kubernetes.default.svc
  project: ecommerce
  source:
    repoURL: https://github.com/dd-shocnt/ecommerce-workshop-discounts-manifests.git
    path: overlays/prod
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
